language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - sunspot/vendor/bundle
    - sunspot_solr/vendor/bundle
    - sunspot_rails/vendor/bundle
  
before_install:
    - gem update --system
    - gem --version

rvm:
  # - 1.9.3
  # - 2.0.0
  - 2.1.0
  - 2.3.1
  - 2.4.3
  - 2.5.1
  # - 2.6.0
  - ruby-head
  # - rbx-2.0
  # - jruby

env:
  - GEM=sunspot UPDATE_FORMAT=xml
  - GEM=sunspot UPDATE_FORMAT=json
  - GEM=sunspot_rails
  - GEM=sunspot_solr
  - SOLR_MODE=cloud GEM=sunspot_rails

matrix:
  allow_failures:
    - rvm: ruby-head
    - env: SOLR_MODE=cloud GEM=sunspot_rails

before_install: 
  - gem install bundler

script:
  - ci/travis.sh

