version: '3'

services:
  zookepper:
    image: zookeeper:latest
    restart: always
    container_name: zookepper
    hostname: zookepper
    ports:
      - "2181:2181"
    networks:
      - local_net
  solr1:
    container_name: solr1
    image: solr:7.6.0
    ports:
     - "8981:8983"
    depends_on:
      - zookepper
    volumes:
      - ./data/sunspot_solr1:/opt/solr/server/solr/mycores
      - ./sunspot_solr/solr/solr/configsets:/etc/configsets
      - ./ci/solr_init.sh:/usr/bin/solr_init.sh
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zookepper:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - local_net
  solr2:
    container_name: solr2
    image: solr:7.6.0
    ports:
     - "8982:8983"
    depends_on:
      - zookepper
    volumes:
      - ./data/sunspot_solr2:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zookepper:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - local_net
  solr3:
    container_name: solr3
    image: solr:7.6.0
    ports:
     - "8983:8983"
    depends_on:
      - zookepper
    volumes:
      - ./data/sunspot_solr3:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zookepper:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - local_net
  solr4:
    container_name: solr4
    image: solr:7.6.0
    ports:
     - "8984:8983"
    depends_on:
      - zookepper
    volumes:
      - ./data/sunspot_solr4:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zookepper:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - local_net
networks:
  local_net:
