version: '3.7'
services:

  app:
    build:
      context: .
    image: sunspot
    volumes:
      - .:/home/app/webapp
    links:
      - solr
    depends_on:
      - solr
    environment:
      - PASSENGER_APP_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - RAILS_APPLICATION_URL=http://sunspot.local
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - SOLR_URL=http://solr:8983/solr/test

  solr:
    image: solr:8
    ports:
      - '9983:8983'
    volumes:
      - ./solr-8-data:/var/solr:cached
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - test
      # note: only one core can be precreated
